version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
    ports:
      - "413:413"
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/wordpress'
    driver: local
  mariadb:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/mariadb'
    driver: local

networks:
  inception:
    driver: bridge
