version: '3'

services:
  mariadb:
    container_name: mariadb
    image: inception:mariadb
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
        - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    image: inception:nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    image: inception:wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/mariadb_vol'
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/wordpress_vol'

networks:
  inception:
    driver: bridge
